### PR TITLE
Installation fixes

### PR DESCRIPTION
**Pull request by CJEBond**
A few fixes I found necessary when creating my own test installation, and updated installation instructions to match.

### CODE REVIEW

**Comment by CJEBond** [comment]
I've edited instructions to reflect that, and restored the database seeder (just implementing fix for filler text length).

**Comment by CJEBond** [comment]
This however raises a new question re: UserDetailsSecretKey
The instructions need further editing to explain where to get this from

**Comment by CJEBond** [comment]
Rebased for good measure

**Comment by Jon-Salmon** [comment]
UserDetailsSecredKey is the auth key in order to use the file on the trevs jcr cis webspace for the authenitificatin. Aquiring a key is currently a case of loging into the webspace and editing the relevelt file

**Comment by CJEBond** [comment]
Is it something that anyone can do, something people can request from you, or not possible for security reasons?

**Pull request merged**
